### ISSUE TITLE
Some problems were found with the configuration of task ':mdsflutter:extractDebugProto' (type 'ProtobufExtract').

### ISSUE THREAD

**Issue by ff225** [petri-lipponen-movesense/mdsflutter#5] opened 2023-10-02 10:07 UTC
i'm developing a flutter app, i'm using mdsflutter: ^1.1.0 (also tried beta) with mdslib-1.10.0(1)-release.aar (also tried mdslib-1.6.0(1)-release.aar, mdslib-3.15.0(1)-release.aar).

i followed the README https://pub.dev/packages/mdsflutter but i get this error.

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':mdsflutter:extractDebugProto' (type 'ProtobufExtract').
  - In plugin 'com.google.protobuf' type 'com.google.protobuf.gradle.ProtobufExtract' property 'destDir' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.5/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - In plugin 'com.google.protobuf' type 'com.google.protobuf.gradle.ProtobufExtract' property 'isTest' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.5/userguide/validation_problems.html#missing_annotation for more details about this problem.

**Comment by petri-lipponen-movesense** [comment] 2023-10-11 06:04
Please try the version 2.0.0-beta2 which has a fixed the issue #4 which I think is duplicate of this one. Also don't use mds libraries older than 1.68.0 or 3.15 (latest is preferred).

**Closed by petri-lipponen-movesense** 2023-10-11 06:04 UTC
